## 4.1 处理缺失值

In [2]:
import pandas as pd
import numpy as np

# 对于数值型数据，pandas使用浮点值NaN来表示缺失值
# 在统计学应用中，NA数据可以是不存在的数据或者是存在但不可观察的数据
# 当清洗数据用于分析时，对缺失数据本身进行分析以确定数据收集问题或数据丢失导致的偏差通常很重要

string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [3]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [6]:
# Python内建的None值对象也被当作NA处理

string_data[0] = None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

### 4.1.1 过滤缺失值

In [7]:
from numpy import nan as NA

data = pd.Series([1, NA, 3.5, NA, 7])
data.dropna() # 在Series上使用dropna来过滤缺失值，它会返回Serie中所有的非空数据及其索引值

0    1.0
2    3.5
4    7.0
dtype: float64

In [8]:
# data.dropna()等价于：
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [9]:
# 处理DataFrame对象时，dropna默认会删除包含缺失值的行
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA], [NA, NA, NA], [NA, 6.5, 3.]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [11]:
cleaned = data.dropna()
cleaned

0    1    2
0  1.0  6.5  3.0

In [13]:
# 传入how='all'时， 删除所有值均为NA的行
cleaned = data.dropna(how='all')
cleaned

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [15]:
# 传入axis=1，以同样的方式删除列
data[4]=NA
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

### 4.1.2 补全缺失值

In [22]:
# 大多数情况下，使用fillna方法来补全缺失值
df = pd.DataFrame(np.random.randn(7, 3))
df[df<0] = NA
df

0         1         2
0  0.234377       NaN       NaN
1       NaN  0.056635  0.605487
2       NaN       NaN       NaN
3  0.689994  0.159214       NaN
4  0.312770       NaN  1.937619
5       NaN  0.132283  1.651190
6       NaN  1.344053       NaN

In [23]:
df.fillna(0) # 调用fillna时，可以使用一个常数来代替缺失值

0         1         2
0  0.234377  0.000000  0.000000
1  0.000000  0.056635  0.605487
2  0.000000  0.000000  0.000000
3  0.689994  0.159214  0.000000
4  0.312770  0.000000  1.937619
5  0.000000  0.132283  1.651190
6  0.000000  1.344053  0.000000

In [27]:
df.fillna({1: 0.5, 2: 0}) # 调用fillna时，可以传入字典，为不同列设定不同的填充值

0         1         2
0  0.234377  0.500000  0.000000
1       NaN  0.056635  0.605487
2       NaN  0.500000  0.000000
3  0.689994  0.159214  0.000000
4  0.312770  0.500000  1.937619
5       NaN  0.132283  1.651190
6       NaN  1.344053  0.000000

In [29]:
df.fillna(0, inplace=True) # 调用fillna时， 传入inplace=True， 进行原位置修改
df

0         1         2
0  0.234377  0.000000  0.000000
1  0.000000  0.056635  0.605487
2  0.000000  0.000000  0.000000
3  0.689994  0.159214  0.000000
4  0.312770  0.000000  1.937619
5  0.000000  0.132283  1.651190
6  0.000000  1.344053  0.000000

In [30]:
df[df==0]=NA

In [31]:
df.fillna(method='ffill') # 调用fillna时，可以传入method参数

0         1         2
0  0.234377       NaN       NaN
1  0.234377  0.056635  0.605487
2  0.234377  0.056635  0.605487
3  0.689994  0.159214  0.605487
4  0.312770  0.159214  1.937619
5  0.312770  0.132283  1.651190
6  0.312770  1.344053  1.651190

### fillna函数参数
参数|描述
:-:|:-:
value|标量值或字典值用于填充缺失值
method|插值方法，默认是'ffill'
axis|需要填充的轴， 默认axis=0
inplace|修改被调用的对象，而不是生成一个备份
limit|用于前向或后向填充时的最大范围

## 4.2 数据转换

### 4.2.1 删除重复值

In [34]:
data = pd.DataFrame({'K1':['one', 'two']*3 + ['two'], 
                     'K2':[1,1,2,3,3,4,4]})
data

K1  K2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [35]:
# DataFrame的duplicated方法返回一个布尔值Series，这个Series反映的每一个行是否存在重复(与之前出现过的行相同)
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [37]:
# DataFrame的drop_duplicates方法返回一个DataFrame， 内容是duplicated返回数组中为False的部分
data.drop_duplicates()

K1  K2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [40]:
data['V1'] = range(7) 
data.drop_duplicates(['K1']) # 可以指定数据的任何子集来检测是否有重复

K1  K2  v1  V1
0  one   1   0   0
1  two   1   1   1

In [45]:
# duplicated和drop_duplicated都是默认保留第一个观测到的值， 传入参数keep='last'将会返回最后一个
print('keep last', data.drop_duplicates(['K1','K2'], keep='last'))
print('keep first', data.drop_duplicates(['K1', 'K2']))

keep last     K1  K2  v1  V1
0  one   1   0   0
1  two   1   1   1
2  one   2   2   2
3  two   3   3   3
4  one   3   4   4
6  two   4   6   6
keep first     K1  K2  v1  V1
0  one   1   0   0
1  two   1   1   1
2  one   2   2   2
3  two   3   3   3
4  one   3   4   4
5  two   4   5   5


### 4.2.2 使用函数或映射进行数据转换

In [46]:
data = pd.DataFrame({'food':['bacon', 'pulled pork', 'bacon', 
                             'Pastrami', 'corned beef', 'Bacon', 
                             'pastrami', 'honey ham', 'nova lox'], 
                     'ounces':[4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [47]:
# 添加一列表明每种肉类的动物来源
# 先写出肉类和动物的映射

meat_to_animal = {'bacon': 'pig',
                  'pulled pork': 'pig',
                  'pastrami': 'cow',
                  'corned beef':'cow',
                  'honey ham':'pig',
                  'nova lox':'salmon'}

In [49]:
# Series的map方法接受一个函数或一个包含映射关系的字典型对象

# 首先统一肉类的大小写
lowercased = data['food'].str.lower()
lowercased

data['animal'] = lowercased.map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

### 4.2.3 替代值

In [50]:
data =  pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [51]:
# 将-999替换为缺失值
data.replace(-999., np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [52]:
# 一次性替换多个值， 可以传入一个列表和替代值
data.replace([-999., -1000.], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [53]:
# 要将不同值替换为不同的值， 可以传入替代值的列表或对应的字典
data.replace([-999., -1000.], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [54]:
data.replace({-999.:np.nan, -1000.:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### 4.2.4 重命名轴索引

In [56]:
# 可以通过函数或者某种形式的映射对轴标签进行转换，生成新的轴标签对象

data = pd.DataFrame(np.arange(12).reshape((3, 4)), index=['Ohio', 'Colorado', 'New York'], 
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [63]:
upper_index = data.index.map(lambda x: x.upper()) 
data.index = upper_index
data

one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [64]:
# 如果想创建数据集转换后的版本，并不修改原有数据集，可以使用rename方法

data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [65]:
# rename可以结合字典对象使用， 为轴标签的子集提供新的值

data.rename(index = {'OHIO':'INDIANA'}, columns={'three':'peekaboo'})

one  two  peekaboo  four
INDIANA     0    1         2     3
COLORADO    4    5         6     7
NEW YORK    8    9        10    11

### 4.2.5 离散化和分箱

In [70]:
# 连续值经常需要离散化，或者分箱操作

# 将年龄数据进行分组，放入离散的年龄框中

ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100] # 分为18-25， 26-35， 36-60及60以上等若干组
cats = pd.cut(ages, bins) # pandas 返回一个特殊的Categorical对象
print(cats)

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]


In [71]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [72]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [74]:
pd.value_counts(cats) # 对pandas.cut结果中的每个箱中的元素进行记数

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [75]:
# 可以通过传递right=False来使分箱区间左闭右开
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [76]:
# 可以通过向labels选项传入一个列表或数组来传入自定义的箱名
group_name=['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_name)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [81]:
# 如果传递给cut整数个的箱来代替显式的箱边，pandas将根据数据中的最大值和最小值计算出等长的箱

data = np.random.rand(20)
pd.cut(data, 4, precision=2)

[(0.56, 0.76], (0.76, 0.95], (0.17, 0.37], (0.56, 0.76], (0.56, 0.76], ..., (0.37, 0.56], (0.17, 0.37], (0.37, 0.56], (0.76, 0.95], (0.17, 0.37]]
Length: 20
Categories (4, interval[float64]): [(0.17, 0.37] < (0.37, 0.56] < (0.56, 0.76] < (0.76, 0.95]]

In [87]:
# qcut基于样本分位数进行分箱
# 取决于样本分布，cut分箱通常不会使每个箱具有相同数据量的点
# 但由于qcut使用样本的分位数，可以获得包含相等数据量的箱

data = np.random.randn(1000) # 正态分布
cats = pd.qcut(data, 4) # 切成四份
pd.value_counts(cats)

(0.647, 4.061]                  250
(0.0201, 0.647]                 250
(-0.65, 0.0201]                 250
(-3.1359999999999997, -0.65]    250
dtype: int64

In [88]:
# 与cut类似，可以传入自定义分位数(0和1之间的数据，包括边)

pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(-1.196, 0.0201], (-1.196, 0.0201], (0.0201, 1.25], (1.25, 4.061], (1.25, 4.061], ..., (-1.196, 0.0201], (0.0201, 1.25], (-1.196, 0.0201], (-1.196, 0.0201], (1.25, 4.061]]
Length: 1000
Categories (4, interval[float64]): [(-3.1359999999999997, -1.196] < (-1.196, 0.0201] < (0.0201, 1.25] < (1.25, 4.061]]

### 4.2.6 检测和过滤异常值

In [89]:
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.050197     0.025724     0.008244    -0.006428
std       1.006396     1.039594     0.977998     0.994482
min      -3.147110    -3.592466    -2.847576    -2.945197
25%      -0.741452    -0.611764    -0.673418    -0.683200
50%      -0.025648     0.006280     0.037886    -0.018853
75%       0.650497     0.691061     0.628502     0.683705
max       3.076591     3.250076     4.082589     2.716266

In [93]:
data[(np.abs(data) > 3).any(axis=1)]

0         1         2         3
231 -0.591145  3.250076 -0.400736  0.945768
379 -0.036696 -3.016957 -0.665368 -0.325208
410  0.297485 -0.354080  4.082589 -0.095808
522  0.552013  1.166395  3.206992  1.349016
790 -0.044095 -3.592466 -0.404234  1.371345
920  3.076591 -0.305568 -0.362513 -0.198839
968 -3.147110  0.775519  2.088351 -0.442749

### 4.2.7 置换和随机抽样

In [97]:
# 使用numpy.random.permutation对DataFrame中的Series或行进行置换(随机排序)是非常方便的
# 调用permutation时根据想要的轴长度可以产生一个表示新顺序的整数数组

df = pd.DataFrame(np.arange(5 * 4).reshape(5, 4))
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [102]:
sampler = np.random.permutation(5)
sampler

array([4, 2, 0, 1, 3])

In [103]:
sampler1 = np.random.permutation(3)
sampler

array([4, 2, 0, 1, 3])

In [104]:
# permutation返回的整数数组可以用在基于iloc的索引或等价的take函数中
df.take(sampler)

0   1   2   3
4  16  17  18  19
2   8   9  10  11
0   0   1   2   3
1   4   5   6   7
3  12  13  14  15

In [105]:
df.take(sampler1)

0  1   2   3
2  8  9  10  11
1  4  5   6   7
0  0  1   2   3

In [106]:
# 可以使用Series和DataFrame的sample方法选出一个随机子集(默认不允许重复选择)

df.sample(n=3)

0   1   2   3
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15

In [107]:
# 可以将replace=True传入sample方法，允许重复选择
df.sample(8, replace=True, axis=1)

2   1   1   2   3   2   2   2
0   2   1   1   2   3   2   2   2
1   6   5   5   6   7   6   6   6
2  10   9   9  10  11  10  10  10
3  14  13  13  14  15  14  14  14
4  18  17  17  18  19  18  18  18

### 4.2.8 计算指标/虚拟变量